//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileUploadData
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileUpload
    {
        public int ID { get; set; }
        public string TransactionId { get; set; }
        public decimal Amount { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string FileType { get; set; }
    }
}
